# Generated by Django 5.1 on 2025-02-13 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_product_description_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
